### PR TITLE
Create bower.js

### PR DESCRIPTION
**Pull request by tibbon**
Created to work with bower and wiredep.

### CODE REVIEW

**Comment by stephen-hill** [comment]
+1

**Comment by nathanboktae** [comment]
@millermedeiros Any reason not to take this? Bower is quite popular....

**Comment by millermedeiros** [comment]
at the time bower was still in flux and I didn't want to maintain multiple `*.json` files.. (harder to update/release new versions..) specially since this file was linked to a specific commit hash.

for some weird reason I was not getting any email notifications for this project, so I missed most of the bug reports/PRs..

if we add the `bower.json` now would it work with all releases? (eg. v0.11.0, v0.12.0, v0.12.1) since the old tags won't have a matching `bower.json` file..

for my own projects I'm basically using npm, volo or [basic shell scripts](https://gist.github.com/millermedeiros/3859714) to manage the dependencies..

since I'm not using crossroads on any project at the moment (working mostly on Firefox OS for the past year and half..) I shifted my focus to other libraries/tasks... that's why things are moving slowly here.

**Comment by nathanboktae** [comment]
Actually I noticed you're already in bower... someone perhaps registered you already? And since you're already tagging repo, you're good. this is a one time thing.

Actually this `bower.json` shouldn't have the version... not sure why. So yes adding a `bower.json` is a one time thing unless your dependencies change. See [angular-ui-router 's bower.json](https://github.com/angular-ui/ui-router/blob/master/bower.json) for an example. I can submit a PR with a cleaner `bower.json`.

**Comment by kennethjor** [comment]
Currently having trouble using Crossroads for a new project because there is no bower.json. Would love to see this PR get accepted.

**Comment by nathanboktae** [comment]
Given how Miller is very busy, for those of you considering router options still, look at [Cherrytree](https://github.com/QubitProducts/cherrytree) - it is actively maintained hierarchal router with a super clean, simple API - `map` to define routes, `use` to add middleware,  `generate` to get a link. That's it. No dependencies, uses Promises instead of a custom pub-sub library.

**Pull request closed without merging**
